---
- name: get the django source
  uri: url=https://www.djangoproject.com/download/1.5.1/tarball/ dest=/opt/django.tgz follow_redirects=yes creates=/opt/django.tgz
  notify: service nginx start/enable

- name: untar django
  command: tar xf /opt/django.tgz -C /opt creates=/opt/Django-1.5.1
  notify: service nginx start/enable

- name: install it
  command: chdir=/opt/Django-1.5.1 python setup.py install creates=/opt/Django-1.5.1/README.rst
  notify: service nginx start/enable

#- name: upgrade
#  command: apt-get upgrade -y

#- name: update
#  command: apt-get update -y

- name: install $items
  apt: pkg=$item state=present
  with_items:
    - python-psycopg2
    - python-pip
    - python-dev
  notify: service nginx start/enable
  tags:
    - aptget

- name: install uwsgi
  pip: name=uwsgi state=present
  notify: service nginx start/enable

- name: get the webapp
  git: repo=git://github.com/fdavis/django-site.git force=yes dest=/opt/mysite
  notify: service nginx start/enable
  tags:
    - gitpull

- name: print out some versions
  shell: python --version; python -c "import django; print django.VERSION"
