---
- name: get the django source
  uri: url=https://www.djangoproject.com/download/1.5.1/tarball/ dest=/opt/django.tgz follow_redirects=yes creates=/opt/django.tgz
  notify: service nginx start/enable

- name: untar django
  command: tar xf /opt/django.tgz -C /opt creates=/opt/Django-1.5.1
  notify: service nginx start/enable

- name: install it
  command: chdir=/opt/Django-1.5.1 python setup.py install creates=/opt/Django-1.5.1/README.rst
  notify: service nginx start/enable

- name: update
  command: apt-get update -y

- name: install python-psycopg2/nginx/mod_python
  apt: pkg=python-psycopg2 state=present
  with_items:
    - python-psycopg2
    - python-pip
  notify: service nginx start/enable

- name: install uwsgi
  pip: name=uwsgi state=present

- name: symlink mod python
  command: ln -s ../mods-available/python.load  /etc/nginx/mods-enabled/python.load creates=/etc/nginx/mods-enabled/python.load
  notify: service nginx start/enable

- name: copy over django site conf
  copy: src=django dest=/etc/nginx/sites-available/django owner=root group=root mode=0644
  notify: service nginx start/enable

- name: symlink sites enabled
  command: ln -s ../sites-available/django /etc/nginx/sites-enabled/000-django creates=/etc/nginx/sites-enabled/000-django
  notify: service nginx start/enable

- name: remove default site symlink
  file: path=/etc/nginx/sites-enabled/000-default state=absent
  notify: service nginx start/enable

- name: print out some versions
  shell: python --version; python -c "import django; print django.VERSION"
